"""Block-art 'GLOW' wordmark for the TUI home screen.

Generated by `figlet -f block -w 200 GLOW`, with one stylistic
fix: the canonical figlet Block G has an open top (it's drawn
as a "C with tongue"), which reads as ambiguous. We close the
top with a horizontal bar so it unambiguously reads as G.

Each line is colored with a single amber accent.
"""

from __future__ import annotations


# ── The 'GLOW' lines ────────────────────────────────────────
# Generated by `figlet -f block -w 200 GLOW`, then row 0 (the
# empty top of G) is filled with `  ████████` to give G its
# missing top bar. The other letters' row 0 stays empty.

GLOW_LINES = [
    "  ████████                                        ",
    "  _|_|_|  _|          _|_|    _|          _|  ",
    "_|        _|        _|    _|  _|          _|  ",
    "_|  _|_|  _|        _|    _|  _|    _|    _|  ",
    "_|    _|  _|        _|    _|    _|  _|  _|    ",
    "  _|_|_|  _|_|_|_|    _|_|        _|  _|      ",
    "                                              ",
    "                                              ",
]
GLOW_WIDTH = 48


def render_glow_block() -> list[str]:
    """Render 'GLOW' as a list of rich-markup lines.

    Coloring strategy:
      - row 0 (top of all caps): brightest amber
      - rows 1-2: soft amber
      - rows 3-5: bright amber (mid-section)
      - rows 6-7: deep amber (bottom)

    Each non-space char gets a rich-markup color tag. Spaces stay.
    """
    bright = "#E8A87C"
    soft = "#F5C7A0"
    deep = "#C97B4F"

    palette = [
        bright,
        soft,
        soft,
        bright,
        bright,
        bright,
        deep,
        deep,
    ]

    lines: list[str] = []
    for r, row in enumerate(GLOW_LINES):
        color = palette[r]
        rendered = ""
        for ch in row:
            if ch == " ":
                rendered += " "
            else:
                rendered += f"[bold {color}]{ch}[/]"
        lines.append(rendered)
    return lines


def render_home_header() -> str:
    """Return the home header: just the 'GLOW' wordmark."""
    return "\n".join(render_glow_block())
