"""The 'GLOW' wordmark for the TUI home screen.

Generated by `figlet -f banner3 -w 200 GLOW`. Each `#` translated
to `█` (full block). Spaces preserved.
"""

from __future__ import annotations


# ── The 'GLOW' lines ────────────────────────────────────────
# Generated by `figlet -f banner3 -w 200 GLOW`, then `#` → `█`.
# 7 rows, all 36 cols.

GLOW_LINES = [
    " ██████   ██        ███████  ██      ██ ",
    "██    ██  ██       ██     ██ ██  ██  ██ ",
    "██        ██       ██     ██ ██  ██  ██ ",
    "██   ████ ██       ██     ██ ██  ██  ██ ",
    "██    ██  ██       ██     ██ ██  ██  ██ ",
    "██    ██  ██       ██     ██ ██  ██  ██ ",
    " ██████   ████████  ███████   ███  ███  ",
]
GLOW_WIDTH = 38


def render_glow_block() -> list[str]:
    """Render 'GLOW' as a list of rich-markup lines.

    Coloring strategy:
      - rows 0-2 (top of all caps): soft amber
      - rows 3-4 (mid-section): bright amber
      - rows 5-6 (bottom): deep amber

    Each non-space char gets a rich-markup color tag. Spaces stay.
    """
    bright = "#E8A87C"
    soft = "#F5C7A0"
    deep = "#C97B4F"

    palette = [
        soft,     # row 0
        soft,     # row 1
        soft,     # row 2
        bright,   # row 3
        bright,   # row 4
        deep,     # row 5
        deep,     # row 6
    ]

    lines: list[str] = []
    for r, row in enumerate(GLOW_LINES):
        color = palette[r]
        rendered = ""
        for ch in row:
            if ch == " ":
                rendered += " "
            else:
                rendered += f"[bold {color}]{ch}[/]"
        lines.append(rendered)
    return lines


def render_home_header() -> str:
    """Return the home header: just the 'GLOW' wordmark."""
    return "\n".join(render_glow_block())
